name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint

  build:
    name: Run Build
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Build
        run: npm run build
