name: Discord Notification on Push

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    if: github.repository == 'depromeet/16th-team3-FE'
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification via curl
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST "$DISCORD_WEBHOOK_URL" \
          -d '{
            "embeds": [{
              "title": "📦 Vercel 배포 알림",
              "description": "'"${BRANCH_NAME}"' 브랜치에 새로운 커밋이 푸시되어 Vercel 배포가 시작되었습니다!",
              "color": 3447003,
              "fields": [
                {
                  "name": "📝 커밋 메시지",
                  "value": "'"${COMMIT_MSG}"'"
                },
                {
                  "name": "👤 작성자",
                  "value": "'"${GITHUB_ACTOR}"'"
                },
                {
                  "name": "🔗 커밋 링크",
                  "value": "'"${COMMIT_URL}"'"
                }
              ]
            }]
          }'