name: Discord Notification on Push

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    if: github.repository == 'depromeet/16th-team3-FE'
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Embed Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            {
              "embeds": [{
                "title": "📦 Vercel 배포 알림",
                "description": "`${{ github.ref_name }}` 브랜치에 새로운 커밋이 푸시되어 Vercel 배포가 시작되었습니다!",
                "color": 3447003,
                "fields": [
                  {
                    "name": "📝 커밋 메시지",
                    "value": "${{ github.event.head_commit.message }}"
                  },
                  {
                    "name": "👤 작성자",
                    "value": "${{ github.actor }}"
                  },
                  {
                    "name": "🔗 커밋 링크",
                    "value": "${{ github.event.head_commit.url }}"
                  }
                ]
              }]
            }