name: git push into another repo to deploy to vercel

on:
 push:
   branches: [dev]

jobs:
 build:
  runs-on: ubuntu-latest
  container: pandoc/latex
  steps:
   - uses: actions/checkout@v2
   - name: Install required packages (Git & Ruby)
     run: |
       apt-get update && apt-get install -y git ruby
       gem install mustache
     run: apk add ruby && gem install mustache
   - name: creates output
     run: sh ./build.sh
   - name: Pushes to another repository
     id: push_directory
     uses: cpina/github-action-push-to-another-repository@main
     env:
      API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
     with:
      source-directory: "output"
      destination-github-username: "ljh130334"
      destination-repository-name: "16th-team3-FE"
      user-email: ${{ secrets.GIT_EMAIL }}
      commit-message: ${{ github.event.commits[0].message }}
      target-branch: main
   - name: Test get variable exported by push-to-another-repository
     run: echo $DESTINATION_CLONED_DIRECTORY
   - name: Push to forked repository
     run: |
      git clone https://github.com/ljh130334/16th-team3-FE.git deployed-repo
      cd deployed-repo
      git remote add forked-repo https://x-access-token:${{ secrets.FORKED_REPO_TOKEN }}@github.com/ljh130334/16th-team3-FE.git
      git config user.name "ljh130334"
      git config user.email "${{ secrets.GIT_EMAIL }}"
      git checkout main
      git pull origin main
      git push -f forked-repo main
     env:
       GITHUB_TOKEN: ${{ secrets.FORKED_REPO_TOKEN }}